#!/usr/bin/env bash

info() {
	if ! tput setaf &> /dev/null
	then
		echo -e "$1"
	else
		echo -e "$(tput setaf 2)$1$(tput sgr0)"
	fi
}

error() {
	if ! tput setaf &> /dev/null
	then
		echo -e "$1" 1>&2
	else
		echo -e "$(tput setaf 1)$1$(tput sgr0)" 1>&2
	fi
}

if (( $# > 0 )) 
then
	info "Installing version: $1"
	version=$1
else
	info "Installing latest version of bashum."
	version="latest" 
fi

if (( $UID == 0 )) 
then
	error "Installing as root is not currently supported."
	exit 1
fi

bashum_file_tmp=${bashum_file_tmp:-/tmp/bashum.tar}
bashum_file_remote=${bashum_file_remote:-"https://github.com/downloads/pkopriv2/bashum/bashum-$version.tar"}

info "Attempting to download bashum file: $bashum_file_remote"
if command -v curl &> /dev/null
then
	if ! curl -L $bashum_file_remote > $bashum_file_tmp
	then
		error "Error downloading: $bashum_file_remote.  Either cannot download or cannot write to file: $bashum_file_tmp"
		exit 1
	fi

elif command -v wget &> /dev/null
then
	if ! wget -q -O $bashum_file_tmp $bashum_file_remote
	then
		error "Error downloading: $bashum_file_remote.  Either cannot download or cannot write to file: $bashum_file_tmp"
		exit 1
	fi

else
	error "This installation requires either curl or wget."
	exit 1
fi


info "Installing bashum."
if ! tar -xf $bashum_file_tmp -C ~
then
	error "Error unpackaging tmp file [$bashum_tmp_file]"
	exit 1
fi 

env_files=( "~/.bashrc" "~/.bash_profile" "~/.zshrc" ) 
for file in "${env_files[@]}"
do
	eval "file=$file" # expand the path correctly

	if [[ ! -f $file ]]
	then
		touch $file 
	fi

	if grep -q "source ~/.bashum/env.sh" $file
	then
		continue
	fi

	info "Adding env entries to: $file"
	cat - >> $file <<-EOF

		# Generated by: bashum
		source ~/.bashum/env.sh
	EOF

	if (( $? )) 
	then 
		error "Error updating file [$file]"
		exit 1
	fi
done

info "Successfully installed bashum!  Please source your environment for changes to take effect. (Start a new terminal session)"
